#! /usr/bin/python
# -*- coding: UTF-8 -*-
"""
Global variables for base module
"""
from django.utils.translation import ugettext_lazy as _
from django.conf import LazySettings

settings = LazySettings()


def get_from_settings_or_default(var_name, default):
    try:
        return settings.__getattr__(var_name)
    except AttributeError:
        return default


# Items by page on paginator views
ITEMS_BY_PAGE = 10

CREATE_SUFFIX = "_create"
LIST_SUFFIX = "_list"
DETAIL_SUFFIX = "_detail"
UPDATE_SUFFIX = "_update"
DELETE_SUFFIX = "_delete"

API_SUFFIX = "_api"
style = "base_django/flexbox"


# Messages
OBJECT_CREATED_SUCCESSFULLY = _("Object created successfully")
OBJECT_UPDATED_SUCCESSFULLY = _("Object updated successfully")
OBJECT_DELETED_SUCCESSFULLY = _("Object deleted successfully")

BASE_MODELS_TRANSLATION_NAME = _("Name")
BASE_MODELS_TRANSLATION_DESCRIPTION = _("Description")
BASE_MODELS_TRANSLATION_SLUG = _("Slug")
BASE_MODELS_TRANSLATION_CREATED = _("Created")
BASE_MODELS_TRANSLATION_MODIFIED = _("Modified")
BASE_MODELS_TRANSLATION_ACTIVE = _("Active")

CONFIGURING_APPLICATION = _("Configuring application {}")
CREATING_PERMISSION_WITH_NAME = _("Creating Permission with name {}")
CREATING_GROUP_WITH_NAME = _("Creating Group with name {}")


COMPETICAO_PREFIX = "COMPETICAO"

COMPETICAO_VERBOSE_NAME = _("Competicao")
COMPETICAO_VERBOSE_NAME_PLURAL = _("Competicao")

COMPETICAO_LIST_URL_NAME = COMPETICAO_PREFIX + LIST_SUFFIX
COMPETICAO_CREATE_URL_NAME = COMPETICAO_PREFIX + CREATE_SUFFIX
COMPETICAO_DETAIL_URL_NAME = COMPETICAO_PREFIX + DETAIL_SUFFIX
COMPETICAO_UPDATE_URL_NAME = COMPETICAO_PREFIX + UPDATE_SUFFIX
COMPETICAO_DELETE_URL_NAME = COMPETICAO_PREFIX + DELETE_SUFFIX
COMPETICAO_LIST_JSON_URL_NAME = COMPETICAO_PREFIX + '_list_json'


TIME_PREFIX = "TIME"

TIME_VERBOSE_NAME = _("Time")
TIME_VERBOSE_NAME_PLURAL = _("Time")

TIME_LIST_URL_NAME = TIME_PREFIX + LIST_SUFFIX
TIME_CREATE_URL_NAME = TIME_PREFIX + CREATE_SUFFIX
TIME_DETAIL_URL_NAME = TIME_PREFIX + DETAIL_SUFFIX
TIME_UPDATE_URL_NAME = TIME_PREFIX + UPDATE_SUFFIX
TIME_DELETE_URL_NAME = TIME_PREFIX + DELETE_SUFFIX
TIME_LIST_JSON_URL_NAME = TIME_PREFIX + '_list_json'


MATCH_PREFIX = "MATCH"

MATCH_VERBOSE_NAME = _("Match")
MATCH_VERBOSE_NAME_PLURAL = _("Match")

MATCH_LIST_URL_NAME = MATCH_PREFIX + LIST_SUFFIX
MATCH_CREATE_URL_NAME = MATCH_PREFIX + CREATE_SUFFIX
MATCH_DETAIL_URL_NAME = MATCH_PREFIX + DETAIL_SUFFIX
MATCH_UPDATE_URL_NAME = MATCH_PREFIX + UPDATE_SUFFIX
MATCH_DELETE_URL_NAME = MATCH_PREFIX + DELETE_SUFFIX
MATCH_LIST_JSON_URL_NAME = MATCH_PREFIX + '_list_json'

